---
title: "05-Data_Compare"
output: html_document
---

# Comparing Data to Priors {-}


```{r, echo = FALSE, warning=FALSE, message=FALSE}
# bety <- betyConnect("/fs/data3/ecowdery/pecan/web/config.php")

pftid <- 1000000131

tropical_species <- tbl(bety, "pfts") %>% dplyr::rename(pft_id = id) %>% filter(pft_id == pftid) %>%
  inner_join(., tbl(bety, "pfts_species"), by = "pft_id") %>% 
  inner_join(., tbl(bety, "species") %>% dplyr::rename(specie_id = id), by = "specie_id") %>% 
  dplyr::select(one_of("pft_id", "name", "specie_id", "genus", "species", "scientificname")) %>% 
  collect()

var <- c(
  "SLA", 
  "wood_density",
  "leaf_elastic_mod", "wood_elastic_mod",
  "leaf_psi_osmotic", "wood_psi_osmotic",
  "rwc_tlp_wood", 
  "leaf_water_sat", "wood_water_sat",
  "leaf_water_cap", "wood_water_cap",
  "leaf_psi_min", "wood_psi_min",
  "leaf_psi_tlp", "wood_psi_tlp",
  "wood_Kmax",
  "wood_psi50",
  "wood_Kexp", 
  "fineroot2leaf"
)

variable_id <- lapply(var, function(v) tbl(bety, "variables") %>% filter(name == v) %>% pull(id)) %>% unlist()

v_df <- data.frame(var, variable_id, stringsAsFactors = FALSE)

species_ids <- unique(tropical_species$specie_id)

trait_data <- tbl(bety, "traits") %>% filter(specie_id %in% species_ids) %>% 
  filter(variable_id %in% v_df$variable_id) %>% collect() %>% left_join(v_df)

```

## Wood Density {-}
```{r plot with data wood_density, echo = FALSE, warning=FALSE, message=FALSE}



wood_density_fit <- pfts_priors %>% filter(var_name == "wood_density") 
wood_density_prior <- rdistn(wood_density_fit) 
wood_density_default <- get_ED_default("/fs/data3/ecowdery/ED.Hydro/parameters/pft3_defaults_history.xml", "rho")

p <- prior_plot(prior = wood_density_prior, 
                plot_default = wood_density_default,
                title = sprintf("(wood_density): %s", wood_density_fit$distn),
                type = "prior")

obs <- trait_data %>% filter(var == "wood_density")
obs$y <- 0
p + geom_density(data = obs, aes(x = mean, fill = "obs"), alpha = .3, color = NA) + 
  geom_point(data = obs, aes(x = mean, y = y), color = "purple4", shape = "|", size = 5)

```





## SLA  {-}
```{r plot with data SLA, echo = FALSE, warning=FALSE, message=FALSE}

SLA_fit <-  pfts_priors %>% filter(var_name == "SLA") 
SLA_prior <- rdistn(SLA_fit) 
SLA_default <- get_ED_default("/fs/data3/ecowdery/ED.Hydro/parameters/pft3_defaults_history.xml", "SLA")

p <- prior_plot(prior = SLA_prior, 
                plot_default = SLA_default,
                title = sprintf("(SLA): %s", SLA_fit$distn),
                type = "prior")

obs <- trait_data %>% filter(var == "SLA")
obs$y <- 0
p + geom_density(data = obs, aes(x = mean, fill = "obs"), alpha = .3, color = NA) + 
  geom_point(data = obs, aes(x = mean, y = y), color = "purple4", shape = "|", size = 5)
```


## leaf_psi_tlp {-}

```{r plot with data leaf_psi_tlp, echo = FALSE, warning=FALSE, message=FALSE}

leaf_psi_tlp_fit <- pfts_priors %>% filter(var_name == "leaf_psi_tlp") 
leaf_psi_tlp_prior <- -rdistn(leaf_psi_tlp_fit) 
leaf_psi_tlp_default <- get_ED_default("/fs/data3/ecowdery/ED.Hydro/parameters/pft3_defaults_history.xml", "leaf_psi_tlp")

p <- prior_plot(prior = leaf_psi_tlp_prior, 
                plot_default = leaf_psi_tlp_default,
                title = sprintf("(leaf_psi_tlp): %s", leaf_psi_tlp_fit$distn),
                type = "prior") 

obs <- trait_data %>% filter(var == "leaf_psi_tlp")
obs$mean <- -obs$mean
obs$y <- 0
p + geom_density(data = obs, aes(x = mean, fill = "obs"), alpha = .3, color = NA) + 
  geom_point(data = obs, aes(x = mean, y = y), color = "purple4", shape = "|", size = 5) +
  xlim(-1000,0)
```


## leaf_water_cap {-}

```{r plot with data leaf_water_cap, echo = FALSE, warning=FALSE, message=FALSE}

leaf_water_cap_fit <- pfts_priors %>% filter(var_name == "leaf_water_cap") 
leaf_water_cap_prior <- rdistn(leaf_water_cap_fit) /1000
leaf_water_cap_default <- get_ED_default("/fs/data3/ecowdery/ED.Hydro/parameters/pft3_defaults_history.xml", "leaf_water_cap")

p <- prior_plot(prior = leaf_water_cap_prior, 
                q = c(0,.99),
                plot_default = leaf_water_cap_default,
                title = sprintf("(leaf_water_cap): %s", leaf_water_cap_fit$distn),
                type = "prior")

obs <- trait_data %>% filter(var == "leaf_water_cap")
obs$y <- 0
obs$mean <- obs$mean / 1000
p + geom_density(data = obs, aes(x = mean, fill = "obs"), alpha = .3, color = NA) + 
  geom_point(data = obs, aes(x = mean, y = y), color = "purple4", shape = "|", size = 5)
```


## wood_psi_tlp {-}

```{r plot with data wood_psi_tlp, echo = FALSE, warning=FALSE, message=FALSE}
wood_psi_tlp_fit <- pfts_priors %>% filter(var_name == "wood_psi_tlp") 
wood_psi_tlp_prior <- -rdistn(wood_psi_tlp_fit) 
wood_psi_tlp_default <- get_ED_default("/fs/data3/ecowdery/ED.Hydro/parameters/pft3_defaults_history.xml", "wood_psi_tlp")

p <- prior_plot(prior = wood_psi_tlp_prior, 
                plot_default = wood_psi_tlp_default,
                title = sprintf("(wood_psi_tlp): %s", wood_psi_tlp_fit$distn),
                type = "prior") 

obs <- trait_data %>% filter(var == "wood_psi_tlp")
obs$mean <- -obs$mean
obs$y <- 0
p + geom_density(data = obs, aes(x = mean, fill = "obs"), alpha = .3, color = NA) + 
  geom_point(data = obs, aes(x = mean, y = y), color = "purple4", shape = "|", size = 5) +
  xlim(-1000,0)
```

## wood_water_cap {-}

```{r plot with data wood_water_cap, echo = FALSE, warning=FALSE, message=FALSE}

wood_water_cap_fit <- pfts_priors %>% filter(var_name == "wood_water_cap") 
wood_water_cap_prior <- rdistn(wood_water_cap_fit) /1000
wood_water_cap_default <- get_ED_default("/fs/data3/ecowdery/ED.Hydro/parameters/pft3_defaults_history.xml", "wood_water_cap")

p <- prior_plot(prior = wood_water_cap_prior, 
                q = c(0,.999),
                plot_default = wood_water_cap_default,
                title = sprintf("(wood_water_cap): %s", wood_water_cap_fit$distn),
                type = "prior")

obs <- trait_data %>% filter(var == "wood_water_cap")
obs$y <- 0
obs$mean <- obs$mean / 1000
p + geom_density(data = obs, aes(x = mean, fill = "obs"), alpha = .3, color = NA) + 
  geom_point(data = obs, aes(x = mean, y = y), color = "purple4", shape = "|", size = 5)
```


## Kmax {-}

```{r plot with data wood_Kmax, echo = FALSE, warning=FALSE, message=FALSE}

wood_Kmax_fit <- pfts_priors %>% filter(var_name == "wood_Kmax") 
wood_Kmax_prior <- rdistn(wood_Kmax_fit) 
wood_Kmax_default <- get_ED_default("/fs/data3/ecowdery/ED.Hydro/parameters/pft3_defaults_history.xml", "wood_Kmax")

p <- prior_plot(prior = wood_Kmax_prior, 
                q = c(0,.99),
                plot_default = wood_Kmax_default,
                title = sprintf("(wood_Kmax): %s", wood_Kmax_fit$distn),
                type = "prior")

obs <- trait_data %>% filter(var == "wood_Kmax")
obs$y <- 0
p + geom_density(data = obs, aes(x = mean, fill = "obs"), alpha = .3, color = NA) + 
  geom_point(data = obs, aes(x = mean, y = y), color = "purple4", shape = "|", size = 5)
```


## psi50 {-}

```{r plot with data wood_psi50, echo = FALSE, warning=FALSE, message=FALSE}

wood_psi50_fit <- pfts_priors %>% filter(var_name == "wood_psi50") 
wood_psi50_prior <- -rdistn(wood_psi50_fit) 
wood_psi50_default <- (-1.09 - (3.57 * wood_density_default ^ 1.73)) * MPa2m

p <- prior_plot(prior = wood_psi50_prior, 
                plot_default = wood_psi50_default,
                title = sprintf("(wood_psi50): %s", wood_psi50_fit$distn),
                type = "prior") 

obs <- trait_data %>% filter(var == "wood_psi50")
obs$mean <- -obs$mean
obs$y <- 0
p + geom_density(data = obs, aes(x = mean, fill = "obs"), alpha = .3, color = NA) + 
  geom_point(data = obs, aes(x = mean, y = y), color = "purple4", shape = "|", size = 5) +
  xlim(-1000,0)

```

## Kexp {-}

```{r plot with data Kexp, echo = FALSE, warning=FALSE, message=FALSE}

wood_Kexp_fit <- pfts_priors %>% filter(var_name == "wood_Kexp") 
wood_Kexp_prior <- rdistn(wood_Kexp_fit) 
wood_Kexp_default <- get_ED_default("/fs/data3/ecowdery/ED.Hydro/parameters/pft3_defaults_history.xml", "wood_Kexp")

p <- prior_plot(prior = wood_Kexp_prior, 
                q = c(0,.99),
                plot_default = wood_Kexp_default,
                title = sprintf("(wood_Kexp): %s", wood_Kexp_fit$distn),
                type = "prior")

obs <- trait_data %>% filter(var == "wood_Kexp")
obs$y <- 0
p + geom_density(data = obs, aes(x = mean, fill = "obs"), alpha = .3, color = NA) + 
  geom_point(data = obs, aes(x = mean, y = y), color = "purple4", shape = "|", size = 5)

```


## Fine root to leaf ratio {-}

```{r plot with data fineroot2leaf, echo = FALSE, warning=FALSE, message=FALSE}

fineroot2leaf_fit <- pfts_priors %>% filter(var_name == "fineroot2leaf") 
fineroot2leaf_prior <- rdistn(fineroot2leaf_fit) 
fineroot2leaf_default <- get_ED_default("/fs/data3/ecowdery/ED.Hydro/parameters/pft3_defaults_history.xml", "q")

p <- prior_plot(prior = fineroot2leaf_prior, 
                q = c(0,.95),
                plot_default = fineroot2leaf_default,
                title = sprintf("(fineroot2leaf): %s", fineroot2leaf_fit$distn),
                type = "prior")

obs <- trait_data %>% filter(var == "fineroot2leaf")
obs$y <- 0
p + geom_density(data = obs, aes(x = mean, fill = "obs"), alpha = .3, color = NA) + 
  geom_point(data = obs, aes(x = mean, y = y), color = "purple4", shape = "|", size = 5)
```
# The Results of the Meta Analysis 

```{r}

library(grid)
traitnames <- read.csv("/fs/data3/ecowdery/ED.Hydro/run_results/pft/ED_tropical_hydro/prior.distns.csv", stringsAsFactors = FALSE) %>% pull(X)

load("/fs/data3/ecowdery/ED.Hydro/run_results/pft/ED_tropical_hydro/madata.Rdata")
load("/fs/data3/ecowdery/ED.Hydro/run_results/pft/ED_tropical_hydro/prior.distns.Rdata")
prior.distns$traits <- traitnames
load("/fs/data3/ecowdery/ED.Hydro/run_results/pft/ED_tropical_hydro/post.distns.Rdata")
post.distns$traits <- traitnames


for(i in seq_along(traitnames)){
  print(i)
  
  pr <- prior.distns %>% filter(traits == traitnames[i])
  po <- post.distns %>% filter(traits == traitnames[i])
  
  same <- 
    pr$distn == po$distn &
    pr$parama == po$parama &
    pr$paramb == po$paramb
  
  if(!same){
    dat <- data.frame(prior = rdistn(pr), 
                      post = rdistn(po) )
    dat2 <- gather(dat)
    
    ED_name1 <- ifelse(traitnames[i] == "fineroot2leaf", "q", traitnames[i])
    ED_name1 <- ifelse(traitnames[i] == "Vcmax", "Vm0", traitnames[i])
    
    ED_name2 <- ifelse(traitnames[i] == "fineroot2leaf", "q", traitnames[i])
    
    plot_default <- get_ED_default("/fs/data3/ecowdery/ED.Hydro/parameters/pft3_defaults_history.xml", ED_name)
    plot_default <- ifelse(ED_name1 =="wood_density", 1, plot_default)
    new_config <- get_ED_default("/fs/data3/ecowdery/ED.Hydro/run_results/run/ENS-00001-1000005005/config.xml", ED_name)
    
    q <- c(0,0.95)
    plot_range <- quantile(dat2$value, q)
    
    p <- ggplot(dat2) + 
      geom_density(aes(x = value, fill = key), alpha = .5)
    
    mainplot <- p + 
      ggtitle(traitnames[i]) + 
      xlim(plot_range)
    
    big <- max(plot_default, new_config)
    small <- min(plot_default, new_config)
    buffer <- (big-small)/10
    
    subplot <- p + 
      geom_vline(aes(xintercept = plot_default, color = "old"), size = 1) + 
      geom_vline(aes(xintercept = new_config, color = "new"), linetype = 1, size = 1) + 
      xlim(small - buffer, big + buffer)
    
    vp <- viewport(width = 0.4, height = 0.4, x = .9,
                   y = .9, just = c("right", "top"))
    
    full <- function() {
      print(mainplot)
      theme_set(theme_bw(base_size = 8))
      print(subplot, vp = vp)
      theme_set(theme_bw())
    }
    
    full()
    
  }
}

```
